### ISSUE TITLE
Consider adding playground to the Hiking Map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#140]
The following is an example of a place where a playground exists, but since there's no indication on the map, it looks a bit odd:
![image](https://user-images.githubusercontent.com/3269297/208100550-a64f1607-c093-4d30-bbed-17a20ab0d329.png)
This is how the same place looks in the Biking Map:
![image](https://user-images.githubusercontent.com/3269297/208100746-85bdc066-ce28-4b12-a5fc-d0350bab1acd.png)

While it's true that this is not very relevant for the Hiking Map in general, I've been to places where knowing there's a playground would help with orientation and also make the trip better when you are accompanied by children.

The main argument for this was in Nesher - where you can finish the hike in a playground (Use the bike map to see the playground at the end of the hike, this playground is mainly in nature as opposed to other cases)
https://israelhiking.osm.org.il/map/20.02/32.7677/35.0308

Another example is אלרוי old train station:
https://israelhiking.osm.org.il/map/16.90/32.7101/35.1042

**Comment by zstadler** [comment]
As far as I remember, the playground symbol was added to the bike map because usually there are drinking water there. The bike map also has several other amenities that bikers may need and do not appear in the Hiking map: shops, first-aid clinics, bike repair shops, and maybe more. All is in line with a different approach of the bike map that is targeting both urban and outdoors bikers and tries to show as many possible relevant amenities as possible.

The hiking map is focused on the outdoors, as such, I feel that children's playgrounds have little value for the outdoor travelers.,

**Comment by zstadler** [comment]
As discussed, playgrounds can be added as an overlay using this shared map - https://israelhiking.osm.org.il/share/XnAktMj9jN
