### ISSUE TITLE
Wider path on high zoom level

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#15]
In IHM map when zooming in a lot the width of the path doesn't change.
This causes the following issues:
1. Inaccurate location since the path is too narrow to cover the inaccuracy
2. Site routes cover the path and it's sometimes hard to tell the underlying color.
3. Site routes precision are not the same and doesn't fall exactly on top of the path.
4. Disorientation - due to the unchanged width I sometime move the map too much or too little since I relay on this for indication on what zoom level I'm in. It is very intuitive and I don't really think about it. But I notice this started to happen often with the vector map.
IMTB map does this, but I think it should be wider than it is today.

Relevant to all types of highways.

**Comment by HarelM** [comment]
Here's my research on this topic:
The following is the raster width of paths and tracks in the raster map when zooming in:
(site zoom: pixels)
**track**: 20: 100, 21: 200, 22: 400, 23: 800
**path**: 20: 40 21: 80, 22: 160, 23: 320
I also looked at the scale to see if we can use "real" values (e.g. 1 meter for path, 5 meter for track):
**track**: 20: 43, 21: 75: 22: 150, 23: 300
**path**: 20: 13, 21: 25, 22: 50, 23: 100

Site's default route width is 9 pixels at any zoom level.

I believe that anything in between the two should be fine, "real" values narrow down too much before getting to zoom 16 so I suggest "in between towards raster" as a solution.
Mapbox zoom = site zoom -1.

**Comment by zstadler** [comment]
As discussed separately, the plan is to set the minimum width of `path` segments to 1 meter and the minimum width of `track` segments to 2 meters. No changes will be made in lower zoom levels where the above width falls below the current settings.

According to the [OSM wiki](https://wiki.openstreetmap.org/wiki/Zoom_levels), at Israel's latitude, 1 pixel is 1 meter in zoom 17.

Notes:
- For simplicity, an [exponential interpolation](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#interpolate) would be best for the higher zoom levels, probably using `base=2` in order to achieve doubling the width at each zoom increase.
- Care should be taken as different highway types reach their minimum width at different zoom levels.
- Similar handling would be expected to other highway types that use `casing`, perhaps in a separate issue.

**Comment by zstadler** [comment]
According to the [OSM wiki](https://wiki.openstreetmap.org/wiki/Zoom_levels), at Israel's latitude, 1 pixel is 1 meter in zoom 17.

The proposed plan is to set the minimum width of `path` segments to 1 meter and the minimum width of `track` segments to 2 meters. No changes will be made in lower zoom levels where the above minimum width is smaller than the current width.

Notes:
- An [exponential interpolation](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#interpolate) would be used with `base=2` in order to achieve doubling the width at each zoom increase.
- Care should be taken as different highway types reach their minimum width at different zoom levels.
- Similar handling would be expected to other highway types. Perhaps in a separate issue, as this requires handling of their `casing` settings.

**Comment by valleyofdawn** [comment]
@HarelM 
I changed the path widths a long time ago in the MTB map. What particularly you think needs improvements.

My guidelines were:
I think we shouldn't follow a mathematical formula for this but test empirically in the field what works best.
The old raster maps paths were definitely too wide in very high zooms.
No need to represent the actual road width, but obviously thickness should represent road hierarchy.
We should keep high visibility but not overwhelm the map with very thick roads at high zooms.

**Comment by HarelM** [comment]
@valleyofdawn I feel it's not wide enough currently for two reasons:
1. When zooming in and the width does not get wide enough I get disoriented, i.e. I fail to easily understand how "deep" I am and panning the map doesn't give the right effect - I pan the map and expect it to move in distance a lot more than I'm actually moving, then I need to zoom out a bit, try again, see that it's still not the right zoom, and kinda iterate the process until I get the right results. This process happens very quickly and I don't need to think about it a lot, same as general orientation, I guess. The fact that I'm not getting used to the current behavior is an indication for me there's something a bit off...
2. less important - GPS precision - when GPS is seen on the map it should be as close to the route as possible (or event on it would be ideal) in all zoom levels, including high levels.

The formula written above are just for guideline to better define what we perceive as the right solution.

As we agreed, this is your call to make, these are just my 2 cents.

**Comment by HarelM** [comment]
![Screenshot_20200626-095151_Israel Hiking Map](https://user-images.githubusercontent.com/3269297/85832043-08df8600-b798-11ea-9ba4-5c0480448510.jpg)

Not sure if this qualifies to this issue but in the above image it's hard to see the roads between the settlements (they are less obvious than tracks). Not sure the zoom level as I was using the app.

Moreover, since the addition of the follow a route feature I usually now plan a route to see the distance left and ETA which makes this feature a lot more important than before, to my perspective of course.

**Comment by HarelM** [comment]
Related request to change the site's UI to solve this issue: #1384.

**Comment by zstadler** [comment]
A preview is available, temporarily, at https://israelhiking.osm.org.il/share/KMQmItr5GI

**Comment by zstadler** [comment]
Thanks @HarelM for your feedback!

Need to adjust items affected by the wider roads:
- National trail width
- Regional trail offset
- Trail names offset
- Density of road shields

To be discussed:
- Should the width increase stop at zoom 21?
- Should the font size of trail names/shields/others increate?

**Comment by HarelM** [comment]
Thanks!! @valleyofdawn I'm guessing this won't hurt the MTB map as well... :-)
