### ISSUE TITLE
Israel Bike Trail - maintenance method 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#151]
A few months ago I arranged IBT in OSM, and Harel could do away with the google sheet.
Have a look at its situation today, when converting it to a trail. It broke to pieces.  Not useful.
I could simply go to each break, and connect it.  But while some OSM data maintenance is normal, seems like the length of the whole relation (403 members) leaves it too vulnerable and it will break again.  

What do you suggest?

![image](https://user-images.githubusercontent.com/49042192/232735109-22a2d76e-7469-4de5-baaf-a2d949b707fa.png)

We also have several relations that represent its different segments. For example from Arad to Nokdim.  We could maybe have the whole IBT as a relation of relations, containing the segment relations. That will not fully solve the above issue. Maybe reduce the work to just mending the segments, but not the main full one again.

Note that someone changed the name of the specific segment relations to also be simply "Israel Bike Trail" so now its difficult to know which is which.  That's unfortunate too.

![image](https://user-images.githubusercontent.com/49042192/232740318-ed364aa2-5cc4-4284-bd01-6f483a989041.png)

**Comment by zstadler** [comment]
Moving to OSM as our data source has advantages, but it also has disadvantages as you found out... As long as we keep using OSM for IBT, it will be necessary to maintain the correctness of this relation. The (hiking) Israel Trail undergoes similar maintenance by some OSM volunteer from time to time.

I find that [Relation Analysis](http://ra.osmsurround.org/analyzeRelation?relationId=6639060&noCache=true&_noCache=on) really helps my find issues in route relation. It shows the relation as a set of (connected) graphs, each with its end nodes.

_Note: The term "graph" here is taken from the "computer science" terminology: a set of nodes connected by lines_

A proper relation should have one graph since all of its segments should be connected. In the current state of IBT, it should have two graphs: for the southern part, and for the part near Arad.

The first graph in the current report for IBT is:

![image](https://user-images.githubusercontent.com/1304610/232797442-47b49b1b-a5dd-43ed-b9fd-32eacf0c187f.png)

_Note: Unfortunately, the line breaks in this report are horrible, so I had to group together the related lines_

- For each connected graph, the report shows all the end points
- This first graph has 3 end nodes. It means that this is not a simple segment, but that it has a Y or T shape. In such a case, I would visit each end node of the graph and see if any of them is an incorrect dead-end.
- For each end point, the report shows the 3 closest end nodes of other graphs
- The first is only 1 meter (0.001 Km) from another node - This is a sign of a small gap.

If you want, we can continue this off-line.

> Note that someone changed the name of the specific segment relations to also be simply "Israel Bike Trail" so now its difficult to know which is which. That's unfortunate too.
See the discussion I've started at https://www.openstreetmap.org/changeset/133955228

**Comment by zstadler** [comment]
@Tsurha 
After fixing the minor gaps, based on the above report, there is a third [IBT compenent](https://israelhiking.osm.org.il/share/t0lRsfbbku) that I could not figure out.

There are also [2 sections of IBT](https://overpass-turbo.eu/s/1tZ8) that do not belong to any Regional Bike Trail.

**Comment by Tsurha** [comment]
Thank you for the maintenance you did!
