### ISSUE TITLE
Weird tile behavior

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#22]
I'm not sure where to report this issue, so I'll start here and we'll see where it should be at the end.
I've came across this rendering:
![image](https://user-images.githubusercontent.com/3269297/82747482-c7774780-9da1-11ea-85a8-1c92b9482f14.png)
The address is this one:
https://israelhiking.osm.org.il/map/14.58/32.5985/35.2370
When moving the map/zoom out/in this gets fixed.
Might have to do with screen resolution, mapbox-gl version, I'm not sure, but I don't have the tool to investigate it.
I hope this is the right place...

**Comment by zstadler** [comment]
- The vector data is there, including stream names that do not show in the trails overlay layer.
- The constant background color is missing 
- It is unclear if the TerrainRGB tiles were successfully downloaded and rendered, because of the flat terrain.

Please check the developer console for any network or console errors when this happens again.

**Comment by HarelM** [comment]
Seems like I can't reproduce anymore...
I do see the tile as grey for a very short time (a few milliseconds) and then it disappears.
Not sure how to classify it.
I'll be closing this issue, in case I see this again I'll reopen.

**Comment by HarelM** [comment]
I don't see any errors in the netwrok tab:
![image](https://user-images.githubusercontent.com/3269297/82750031-2e9ef700-9db6-11ea-81fe-11022d5e0b0d.png)
The console has this warning though:
[.WebGL-000002D12E83DE50] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.

**Comment by zstadler** [comment]
This is a browser bug. Closing
