### ISSUE TITLE
Reduce generalization (Douglass Parker) tolerance

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#24]
I get the feeling the map is "too" sharp from time to time, mainly when looking at it in low zoom levels.
Let's look at the following example (even though it is in the MTB map):
While the nature reserve (נחל שעל) is probably very accurate it looks very sharp in terms of polygon corners.
I'm not sure, but maybe trying to use rounded corners somehow?
![image](https://user-images.githubusercontent.com/3269297/82790457-c236fd00-9e74-11ea-95fb-b683c8bcaa49.png)
https://israelhiking.osm.org.il/map/14.68/33.0341/35.2194

Here's another small example:
![image](https://user-images.githubusercontent.com/3269297/82790829-66b93f00-9e75-11ea-8647-c27c2e045434.png)

I admit I don't know what should be the right solution, but I wanted to share the feeling I get...

**Comment by zstadler** [comment]
A similar comment was made about the contour lines. All these cases are due to the over-simplification of the lines done in the creation process of the lower zoom levels of the vector tiles. The resolution of the simplifications can be tuned. 
In both maps above we see other features that do not have such sharp corners.
Reducing the simplification will increase the tile size, and therefore should be done carefully.

BTW, Mapbox style not have rounding of lines similar to Maperitive.

**Comment by zstadler** [comment]
@HarelM,
Each layer has its own tolerance definition. 
In your opinion, which layers/map elements require a tolerance reduction?

BTW, while handling #37, I've reduced the tolerance for the contour lines.

**Comment by HarelM** [comment]
The following feels like they are over simplified to me:
1. tracks, footways, paths (mainly those that has color and are visible in lower zooms)
2. Nature reserve (mainly in the IMTB map, in the IHM map they are now only contour so it's a lot less obvious).
I don't see other stuff but I haven't looked deep in both maps.
Maybe @valleyofdawn has some input here...

**Comment by zstadler** [comment]
1. The thin colored trails, visible in some lower zooms, are produced by the `trail` layer.
2. Both maps are using the same `parks` layer.

I'll reduce their generalization tolerance.

**Comment by zstadler** [comment]
The tolerance for the `trails` and `parks` layers was reduced by 2x and 4x , respectively.
