### ISSUE TITLE
Center barrier icon (and maybe other icons)

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#63]
When zooming in to max (zoom 23) the following is how the barrier looks - see screenshot below.
I thought I misplaced it when I mapped it, but checking in OSM shows the barrier is on the line and not beside it, like the icon is "feeling"
This is nit-picking, I know, I just wanted to open an issue so we won't forget.
https://israelhiking.osm.org.il/map/23.00/32.5941/35.0618
![image](https://user-images.githubusercontent.com/3269297/97144313-e45ae100-176c-11eb-9d4f-136d5e8cfe26.png)

**Comment by zstadler** [comment]
This issue is unrelated to the map style. The gap can be seen in the vector tile inspector of Maputnik:

![image](https://user-images.githubusercontent.com/1304610/97147702-9517af00-1772-11eb-9849-79b4988cfb0d.png)

It is probably a rounding artifact caused by the Mapbox library or OpenMapTiles' vector tile generation flow.

**Comment by zstadler** [comment]
BTW, The gap is about 30 cm
![image](https://user-images.githubusercontent.com/1304610/97148742-4ec34f80-1774-11eb-9174-2b18f387d887.png)
