### ISSUE TITLE
Create Hebrew glyph file

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/VectorMap#7]
The current file we use is:
https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf
It contains the open sans font family, which I used.
It provides different results in Hebrew in Maputnik (MapBox rendering) and in stackblitz (OpenLayers rendering).
I suspect that the font does not include Hebrew and each renderer substitutes it with another fall-back font.
Building a glyph is not trivial. There is some information here:
https://github.com/mapbox/node-fontnik

Free google font families (that include Hebrew) I'd like to use are:
'Arimo',  'Secular One', and  'Assistant'.
More are available here:
http://fontim.co.il/

**Comment by valleyofdawn** [comment]
Solved with regular css fonts

**Comment by valleyofdawn** [comment]
We may need to revisit this for off-line capabilities

**Comment by HarelM** [comment]
Fonts are stored in the site now, I downloaded only open San regular and bold. There's a lot of files there, I do not wish to bundle them all so I hand picked only the fonts you use.
If this changes let me know.
Glyphs and sprite properties are ignored in the style you set in order to support offline capabilities.

**Comment by zstadler** [comment]
AFAIK, there is no issue with Hebrew fonts in the map in  both online and offline modes.
Closing
